# Generated by Django 6.0.1 on 2026-01-18 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_hostelimage_and_more'),
    ]

    operations = [
    ]
